### ISSUE TITLE
Optimizing NodeJS with BOLT

### ISSUE THREAD

**Issue by gabrielschulhof** [aaupov/aaupov.github.io#1]
I tried reproducing the procedure you used in your post at https://aaupov.github.io/blog/2020/10/08/bolt-nodejs. I found that, unless I build with `gcc -no-pie -fno-PIE` and `g++ -no-pie -fno-PIE` `perf2bolt` crashes with a failed assertion:

```
Assertion `MemType == MemoryContentsType::POSSIBLE_PIC_JUMP_TABLE && "PIC jump table heuristic failure"' failed.
```

It might be helpful to update your post to mention that, for `perf2bolt` to work correctly, one should turn off PIE during build.

**Comment by aaupov** [comment]
Hi Gabriel!

Sorry for getting back so late, I think I've missed the notification that the issue was open in this repo.

> I tried reproducing the procedure you used in your post at https://aaupov.github.io/blog/2020/10/08/bolt-nodejs. I found that, unless I build with `gcc -no-pie -fno-PIE` and `g++ -no-pie -fno-PIE` `perf2bolt` crashes with a failed assertion:
> 
> ```
> Assertion `MemType == MemoryContentsType::POSSIBLE_PIC_JUMP_TABLE && "PIC jump table heuristic failure"' failed.
> ```
> 
> It might be helpful to update your post to mention that, for `perf2bolt` to work correctly, one should turn off PIE during build.

Good catch. Our open-source tests caught up to include these compilation flags to run successfully on Ubuntu 20.04. Perhaps the Ubuntu version I've used didn't have these flags on by default.
